version: "3.1"
services:
  proxy:
    image: nginx:1.15-alpine
    ports:
      - "8080:80"
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf/domain.conf:/etc/nginx/domain.conf:ro
    depends_on:
      - projekt
      - person

  # ========================================
  # Falls Sie das Person-SCS implementieren,
  # überschreiben Sie diesen Teil
  person:
    build: ./person-scs
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}

  persondb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=postgres
    volumes:
      - ./person-scs/data:/var/lib/postgresql/data

  # ========================================
  # Falls Sie das Projekt-SCS implementieren,
  # überschreiben Sie diesen Teil
  projekt:
    image: hashicorp/http-echo
    command: -listen=:8080 -text="Hello from projekt"

  projektdb:
    image: hashicorp/http-echo
    command: -listen=:3306 -text="I am just a dummy"
  # ========================================
